[module/date]
type = internal/date
interval = 1

time = "   %a, %b %d  %H:%M:%S "
;time-alt = " %H:%M"

format-background = ${colors.grey-9}
format-foreground = ${colors.blue-a1}
label = %{T2}%time%%{T-}
