[module/launcher]
type = custom/text

click-left = sh ~/.config/rofi/bin/launcher_blurry_full 
;click-right= rofi -show run
;click-middle = rofi -show window
content = %{T2} %{T-}
content-background = ${colors.grey-9}
content-foreground = ${colors.cyan-a1}
