[module/mpd]
type = internal/mpd

host = 127.0.0.1
port = 6600

; Format
format-online = <label-song> <label-time><toggle><icon-prev><icon-next><icon-repeat><icon-random>
format-online-background = ${colors.grey-9}
format-paused = <label-song> <label-time><toggle><icon-prev><icon-next><icon-repeat><icon-random>
format-paused-background = ${colors.grey-9}
format-padding = 1
;format-stoped = <toggle> <icon-prev> <label-song> <icon-next> <icon-stop> | <bar-progress> | <icon-repeat> <icon-random>
;format-paused = <toggle> <icon-prev> <label-song> <icon-next> <icon-stop>
;format-stopped =  <toggle>

;label-song-underline = ${colors.nord8}
;label-song = %artist:0:10:...% - %title:0:10:...%
label-song = %{T2}%title:0:20:%%{T-}

icon-play = %{T2} %{T-}
icon-play-foreground = ${colors.red-a1}
icon-play-margin-left = 1
icon-pause = %{T2} %{T-}
icon-pause-foreground = ${colors.blue-a2}
icon-pause-margin-left = 1
icon-stop =  
icon-stop-foreground = ${colors.blue-a1}
icon-stop-margin = 1
icon-prev = %{T2} %{T-}
icon-prev-foreground = ${colors.blue-a1}
icon-prev-margin-left = 1
icon-next = %{T2} %{T-}
icon-next-foreground = ${colors.blue-a1}
icon-next-margin-left = 1
icon-repeat = %{T2} %{T-}
icon-repeat-margin = 1
icon-random = %{T2}  %{T-}
icon-random-margin-right = 1

toggle-on-foreground = ${colors.green-a1}
toggle-off-foreground = ${colors.red-a1}

label-time = %elapsed%/%total%
