alias pchains='proxychains4 -q'
alias pdoom='pchains doom'
alias pacun='sudo pacman -Rns'
alias pacs='yay -Ss'
alias pacU='yay -Syu'
alias paci='yay -S'
alias pacq='pacman -Si'
alias pacQ='yay -Qi'
alias pacS='yay -Ss'
alias gd='git clone --depth 1'
alias gc='git clone'
alias gsp='git submodule foreach git pull'
alias ipy='ipython'
alias py='python'
alias ra='ranger'
alias sra='sudo -E ranger'
alias vim='nvim'
alias sudo='sudo -E'
alias reload='source ~/.zshrc'
alias fcapp='flutter create --template=app --project-name'
alias fcmodule='flutter create --template=module --project-name'
alias fcpackage='fluter create --template=package --project-name'
alias fcplugin='flutter create --template=plugin --project-name'
alias frunh='flutter run -d CSX' #华为手机
alias cdiff='colordiff'
alias ex='exit'
alias reboot='sync & reboot'
alias la='lazygit'
